### ISSUE TITLE
Deadlock when resizing font on OSX 10.6

### ISSUE THREAD

**Issue by stefanoborini** [stefanoborini/vai#147]
Thread 2 (process 53782):
#0  0x00007fff86e65a6a in __semwait_signal ()
#1  0x00007fff86e69881 in _pthread_cond_wait ()
#2  0x000000010011eccb in PyThread_acquire_lock_timed (lock=0x101870bd0, microseconds=-1, intr_flag=1) at thread_pthread.h:500
#3  0x00000001001249c8 in acquire_timed (lock=0x101870bd0, microseconds=-1) at ./Modules/_threadmodule.c:71
#4  0x0000000100124d09 in lock_PyThread_acquire_lock (self=0x101735b20, args=<value temporarily unavailable, due to optimizations>, kwds=<value temporarily unavailable, due to optimizations>) at ./Modules/_threadmodule.c:139
#5  0x00000001000df1ab in PyEval_EvalFrameEx (f=0x102109718, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4227
#6  0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x1007d81e0, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=2, kws=0x10212e858, kwcount=0, defs=0x1007ded80, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#7  0x00000001000def77 in fast_function [inlined] () at /Users/sbo/Downloads/Python-3.4.0/Python/ceval.c:4334
#8  0x00000001000def77 in PyEval_EvalFrameEx (f=0x10212e6b8, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4252
#9  0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x1007d8c00, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=1, kws=0x1021005c0, kwcount=0, defs=0x1007eaa00, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#10 0x00000001000def77 in fast_function [inlined] () at /Users/sbo/Downloads/Python-3.4.0/Python/ceval.c:4334
#11 0x00000001000def77 in PyEval_EvalFrameEx (f=0x102100418, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4252
#12 0x00000001000df111 in PyEval_EvalFrameEx (f=0x102100058, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4324
#13 0x00000001000df111 in PyEval_EvalFrameEx (f=0x10190bda0, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4324
#14 0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x1007da930, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=1, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#15 0x000000010003958a in function_call (func=0x1007f1d08, arg=0x100618fd0, kw=0x0) at Objects/funcobject.c:632
#16 0x0000000100007908 in PyObject_Call (func=0x1007f1d08, arg=0x100618fd0, kw=0x0) at Objects/abstract.c:2067
#17 0x00000001000232ec in method_call (func=0x1007f1d08, arg=0x10031e048, kw=0x0) at Objects/classobject.c:347
#18 0x0000000100007908 in PyObject_Call (func=0x1013bac88, arg=0x10031e048, kw=0x0) at Objects/abstract.c:2067
#19 0x00000001000d5b17 in PyEval_CallObjectWithKeywords (func=0x1013bac88, arg=0x10031e048, kw=0x0) at Python/ceval.c:4104
#20 0x0000000100124657 in t_bootstrap (boot_raw=0x101814d20) at ./Modules/_threadmodule.c:999
#21 0x00007fff86e63fd6 in _pthread_start ()
#22 0x00007fff86e63e89 in thread_start ()

Thread 1 (process 53782):
#0  0x00007fff86e65a6a in __semwait_signal ()
#1  0x00007fff86e69881 in _pthread_cond_wait ()
#2  0x000000010011eccb in PyThread_acquire_lock_timed (lock=0x1018c26f0, microseconds=-1, intr_flag=1) at thread_pthread.h:500
#3  0x00000001001249c8 in acquire_timed (lock=0x1018c26f0, microseconds=-1) at ./Modules/_threadmodule.c:71
#4  0x0000000100124d09 in lock_PyThread_acquire_lock (self=0x1014b0508, args=<value temporarily unavailable, due to optimizations>, kwds=<value temporarily unavailable, due to optimizations>) at ./Modules/_threadmodule.c:139
#5  0x00000001000df1ab in PyEval_EvalFrameEx (f=0x1018ad348, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4227
#6  0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x1007d81e0, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=2, kws=0x1018c2b78, kwcount=0, defs=0x1007ded80, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#7  0x00000001000def77 in fast_function [inlined] () at /Users/sbo/Downloads/Python-3.4.0/Python/ceval.c:4334
#8  0x00000001000def77 in PyEval_EvalFrameEx (f=0x1018c29d8, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4252
#9  0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x1007d8c00, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=1, kws=0x10189ef40, kwcount=0, defs=0x1007eaa00, defcount=1, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#10 0x00000001000def77 in fast_function [inlined] () at /Users/sbo/Downloads/Python-3.4.0/Python/ceval.c:4334
#11 0x00000001000def77 in PyEval_EvalFrameEx (f=0x10189edb8, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4252
#12 0x00000001000df111 in PyEval_EvalFrameEx (f=0x10125ac08, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4324
#13 0x00000001000df111 in PyEval_EvalFrameEx (f=0x1003bf438, throwflag=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:4324
#14 0x00000001000e03dd in PyEval_EvalCodeEx (_co=0x100526390, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>, args=<value temporarily unavailable, due to optimizations>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
#15 0x00000001000e049f in PyEval_EvalCode (co=<value temporarily unavailable, due to optimizations>, globals=<value temporarily unavailable, due to optimizations>, locals=<value temporarily unavailable, due to optimizations>) at Python/ceval.c:773
#16 0x000000010010a41e in run_mod [inlined] () at /Users/sbo/Downloads/Python-3.4.0/Python/pythonrun.c:2175
#17 0x000000010010a41e in PyRun_FileExFlags (fp=0x7fff70cc9f60, filename_str=<value temporarily unavailable, due to optimizations>, start=<value temporarily unavailable, due to optimizations>, globals=0x1003bb648, locals=0x1003bb648, closeit=1, flags=0x7fff5bfff580) at Python/pythonrun.c:2128
#18 0x000000010010a7cd in PyRun_SimpleFileExFlags (fp=0x7fff70cc9f60, filename=0x10051e520 "/Users/sbo/bin/vai", closeit=1, flags=0x7fff5bfff580) at Python/pythonrun.c:1601
#19 0x0000000100121b75 in Py_Main (argc=<value temporarily unavailable, due to optimizations>, argv=0x1004060e0) at Modules/main.c:319
#20 0x0000000100000b12 in main (argc=3, argv=0x7fff5bfff648) at ./Modules/python.c:69

**Comment by stefanoborini** [comment]
Likely to be due to #156  root cause. Closing
