### ISSUE TITLE
_curses.error: addwstr() returned ERR

### ISSUE THREAD

**Issue by Jb00** [stefanoborini/vai#160]
I am seeing this issue. To install it, I did ; pip3.4 install vai and it went fine. 

I though issue 149 was the same,  but it looks different.

Thanks, 

Apologies. Vai has crashed.
---------------------------
Traceback (most recent call last):
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vai/__init__.py", line 46, in main
    app.exec_()
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 83, in exec_
    self.processEvents(True)
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 99, in processEvents
    self._sendPaintEvents()
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 284, in _sendPaintEvents
    w.event(events.VPaintEvent())
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VWidget.py", line 168, in event
    self.paintEvent(event)
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vai/widgets/SideRuler.py", line 40, in paintEvent
    + self._icons["SideRuler.border"]))
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VPainter.py", line 30, in drawText
    self._widget.screenArea().write(pos_or_rect, string, self.fg_color, self.bg_color)
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VScreen.py", line 301, in write
    bg_color)
  File "/ws/jeaubin-ott/py3/lib/python3.4/site-packages/vaitk/gui/VScreen.py", line 109, in write
    self._curses_screen.addstr(y, x, out_string, attr)
_curses.error: addwstr() returned ERR

**Comment by stefanoborini** [comment]
@stoic: Checking it. I think the nature of the problem is the same, that is, wide character support. In reality it's probably due to #148 . The underlying point is that some linux/python installations link against the "ascii" ncurses, not ncursesw (which is the one with wide character support). I deployed an automatic workaround in the very latest commit, but it's untested and you would have to get the git version. I am writing some tests for that patch, but I don't have a broad collection of linux to test it on, so I am stuck for releasing 1.5 until I get back from vacation.

I suggest the following: try first the workaround suggested by #148. If it doesn't work, please let me know and I will investigate further. 

Two questions: what linux distribution do you have, and what do you obtain from echo $TERM?

Thank you.

**Comment by Jb00** [comment]
Hi, 

Thanks for the quick answer. I've installed from latest master,  and it works now. So your fix works :) Though I understand it is not the final patch,  no worries. I wont use it for anything production yet. 

Red Hat Enterprise Linux Client release 5.5 (Tikanga)  (Work linux)
xterm

Thanks,

**Comment by stefanoborini** [comment]
Good to know. Thanks!
