### ISSUE TITLE
Opening a file with relative import

### ISSUE THREAD

**Issue by jeaubin** [stefanoborini/vai#169]
When doing 

vai file and file contains relative import, it crash with follow error :

If go back down 1 level, and open it, then it works. 

vai base.py

Traceback (most recent call last):
  File "...bin/vai", line 9, in <module>
    load_entry_point('vai==1.4', 'console_scripts', 'vai')()
  File "...lib/python3.4/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "...lib/python3.4/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "...lib/python3.4/site-packages/pkg_resources.py", line 2048, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/__init__.py", line 96, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/EditorApp.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/Editor.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/controllers/__init__.py", line 3, in <module>
    from .commons import CommonSetup, CommonVerify, CommonCleanup
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/controllers/EditorController.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/linting/__init__.py", line 2, in <module>

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "...lib/python3.4/site-packages/vai-1.4-py3.4.egg/vai/linting/PyFlakesLinter.py", line 2, in <module>
  File "...lib/python3.4/site-packages/pyflakes/api.py", line 11, in <module>
    from pyflakes import checker, __version__
  File "...lib/python3.4/site-packages/pyflakes/checker.py", line 7, in <module>
    import doctest
  File "...python-3.4.1/lib/python3.4/doctest.py", line 105, in <module>
    import unittest
  File ".../.../unittest/**init**.py", line 2, in <module>
    from .testcase import TestCase
  File ".../.../unittest/testcase.py", line 4, in <module>
    from ..decorator import loop
ValueError: attempted relative import beyond top-level package

**Comment by stefanoborini** [comment]
There's something strange. I tried to reproduce it but I couldn't, but the main issue seems to be due to a spurious package of some sort.

I need more info for this bug, but the last lines of the traceback are rather interesting: pyflakes is trying to import doctest from the python standard library. doctest imports unittest, which should resolv to the standard library unittest module. However, the aetest/unittest is imported, from a package I can't identify (ae = appengine?). The three "ats" characters don't allow me to understand what is happening. Google code search didn't help.

In any case, I suspect some sort of module takeover, and the exception is accidental and due to the consequences of this takeover. We might have to workaround the occurrence of this takeover, if we can have some form of control over it (e.g. verifying module path resolution order at startup time).

I wait for more information on this, for now it's on hold.

**Comment by Jb00** [comment]
It is a local package that I can't share. I am not sure what you mean by takeover. I should have some time tomorrow to work on it, if you are available we could chat about it.

**Comment by stefanoborini** [comment]
it means that it is probably coming earlier in the python sys.path, and therefore its lookup priority comes earlier than the one of vai when import is executed. It's definitely a bug, but it's unclear to me how it comes into being.
