### ISSUE TITLE
vai crashes if command cannot be recognized

### ISSUE THREAD

**Issue by alessio** [stefanoborini/vai#201]
Just open vai, then ":" and type any unrecognized command shortcut, e.g. 'a'.

```sh
(.env) alessio@soqtl021:~$ vai
Apologies. Vai has crashed.
---------------------------
Traceback (most recent call last):
  File "/home/alessio/.env/lib/python3.4/site-packages/vai/__init__.py", line 109, in main
    app.exec_()
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 114, in exec_
    self.processEvents(True)
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 121, in processEvents
    self._processKeyEvents()
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 239, in _processKeyEvents
    self._processSingleKeyEvent(event)
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/gui/VApplication.py", line 262, in _processSingleKeyEvent
    widget.keyEvent(key_event)
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/gui/widgets/VLineEdit.py", line 130, in keyEvent
    self.returnPressed.emit()
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/core/VSignal.py", line 25, in emit
    slot(*args, **kwargs)
  File "/home/alessio/.env/lib/python3.4/site-packages/vaitk/core/VSignal.py", line 25, in emit
    slot(*args, **kwargs)
  File "/home/alessio/.env/lib/python3.4/site-packages/vai/controllers/CommandBarController.py", line 25, in parseCommandBar
    if self._interpretLine(command_text):
  File "/home/alessio/.env/lib/python3.4/site-packages/vai/controllers/CommandBarController.py", line 87, in _interpretLine
    return self._editor_controller.interpretCommandLine(command_text)
  File "/home/alessio/.env/lib/python3.4/site-packages/vai/controllers/EditorController.py", line 158, in interpretCommandLine
    plugin_object = self._keyword_to_plugin_cache[keyword]
KeyError: 'a'

---------------------------
Your buffers have been dumped to the following files

  /home/alessio/vaidump-noname-23944.txt

The traceback has been saved in vai_crashreport.out
```

**Comment by stefanoborini** [comment]
Confirmed.
