### ISSUE TITLE
any not an editor command crashes vai

### ISSUE THREAD

**Issue by Euphorbium** [stefanoborini/vai#215]
When I enter any nonsense in normal mode after the column I get: (The crashreport is empty.)

     Apologies. Vai has crashed.
     ---------------------------
     Traceback (most recent call last):
       File "/usr/local/lib/python3.4/dist-packages/vai/__init__.py", line 109, in main
         app.exec_()
       File "/usr/local/lib/python3.4/dist-packages/vaitk/gui/VApplication.py", line 114, in exec_
         self.processEvents(True)
       File "/usr/local/lib/python3.4/dist-packages/vaitk/gui/VApplication.py", line 121, in processEvents
         self._processKeyEvents()
       File "/usr/local/lib/python3.4/dist-packages/vaitk/gui/VApplication.py", line 239, in _processKeyEvents
         self._processSingleKeyEvent(event)
       File "/usr/local/lib/python3.4/dist-packages/vaitk/gui/VApplication.py", line 262, in _processSingleKeyEvent
         widget.keyEvent(key_event)
       File "/usr/local/lib/python3.4/dist-packages/vaitk/gui/widgets/VLineEdit.py", line 130, in keyEvent
         self.returnPressed.emit()
       File "/usr/local/lib/python3.4/dist-packages/vaitk/core/VSignal.py", line 25, in emit
         slot(*args, **kwargs)
       File "/usr/local/lib/python3.4/dist-packages/vaitk/core/VSignal.py", line 25, in emit
         slot(*args, **kwargs)
       File "/usr/local/lib/python3.4/dist-packages/vai/controllers/CommandBarController.py", line 25, in parseCommandBar
         if self._interpretLine(command_text):
       File "/usr/local/lib/python3.4/dist-packages/vai/controllers/CommandBarController.py", line 87, in _interpretLine
         return self._editor_controller.interpretCommandLine(command_text)
       File "/usr/local/lib/python3.4/dist-packages/vai/controllers/EditorController.py", line 158, in interpretCommandLine
         plugin_object = self._keyword_to_plugin_cache[keyword]
     KeyError: 'asdasd'
     
     ---------------------------
     Your buffers have been dumped to the following files
     
       /home/euphorbium/vaidump-asdasd.txt-81076.txt
     
     The traceback has been saved in vai_crashreport.out

**Comment by stefanoborini** [comment]
That's fixed in git.
