### ISSUE TITLE
Vai complains something about vaitk, problems with installation

### ISSUE THREAD

**Issue by PeterFillerman** [stefanoborini/vai#223]
Hello. I have problems with installing vai. After getting vai's source from git, I tried to run setup.py, and got "Python 3.4 required". I downloaded lastest 3.5 python from the official site, compiled it from source, and installed it. I run setup.py again, and got "Python 3.4 required". After that, I opened setup.py and deleted the version check. After that, I made setup.py build and sudo setup.py install. After running vai, I got this:

$ vai
Traceback (most recent call last):
  File "/usr/local/bin/vai_exec", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vaitk==1.7' distribution was not found and is required by vai

**Comment by stefanoborini** [comment]
you need to install vaitk. It's on https://github.com/stefanoborini/vaitk but I suggest you use pip.

**Comment by anddam** [comment]
What's keeping vai at 3.4?

**Comment by stefanoborini** [comment]
@anddam I tried to stay with the most recent python version when I started, but now that asyncio is out, I was willing to consider redesigning the event loop and the overall design with coroutines. Problem is, I lost interest in the project, mostly because I decided to use pycharm, didn't see a lot of interest in the project from outside, and focused on other things.
